version: '3.8'

# Launch mlflow server
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.2 # Pre-built MLflow image
    ports:
      - "5001:5000"  # Expose port 5000 in the container to 5001 on the host
    volumes:
      - ./mlruns:/mlruns  # Mount local folder for MLflow artifacts
    environment:
      #- MLFLOW_TRACKING_URI=sqlite:///mlflow/mlflow.db  # Using SQLite as backend for tracking
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlruns/artifacts  # Path for artifact storage
    command:
      mlflow server --backend-store-uri sqlite:///mlruns/mlflow.db --host 0.0.0.0 --port 5000 

  #Train the model
  trainings:
    image: jeanluc073/model_dev-trainings
    volumes:
     #- ./:/src/model_dev  # Mount current directory for code and data
      - ./mlruns:/mlruns #Allows to get all the result inside the trainings container
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000  # Set MLflow server location
      - PATH=/src/model_dev/venv/bin:$PATH
    command:
      python3 train.py

    depends_on:
      - mlflow  # Ensure mlflow starts first
    #runtime: nvidia
