name: CI-CD Pipeline

on:
  push

jobs:
  #Checking-code-quality:
    #runs-on: ubuntu-latest
    #steps:
    
      # Action 1: Pull the code from GitHub
      #- name: Checkout code
        #uses: actions/checkout@v3
       
      # Action 2: Installation of Python and pip
      #- name: Install Python and pip
        #uses: actions/setup-python@v3
        #with:
          #python-version: '3.12.6'  # Use quotes around the version
         
      # Action 3: Installation of dependencies
      #- name: Install dependencies
        #run: |
          #pip install pylint
          #pip install -r ./model_dev/requirements.txt
         
      # Action 4: Run pylint
      #- name: Run pylint
        #run: pylint model_dev/train.py
    
  launch-training:
    runs-on: self-hosted  # Or use 'ubuntu-latest' if you're not using a self-hosted runner
    defaults:
     run:
      working-directory: ./model_dev

    steps:

      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password from GitHub Secrets

      # Step 3: Build Docker image for training
      - name: Build Docker image for training
        run: |
          docker build -t model_dev_2 .
        
      # Build, train model, tag and push the Docker image for the model
      - name: Run training and generate artifacts
        run: |
          docker volume create mlruns_vol
          docker run -d --gpus all -p 5000:5000 -v mlruns_vol:/src/model_dev/mlruns_tmp model_dev_2 sh run.sh
          docker exec $(docker ps -alq) cp -r mlruns_tmp /src/app/mlruns
          docker commit $(docker ps -alq) model_dev_2 
          docker tag model_dev_2:latest ${{ secrets.DOCKER_USERNAME }}/model_dev_2:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/model_dev_2:latest

      # Build, mount volume, tag and push the Docker image for the app
      - name: Build Docker image for app
        working-directory: /home/ubuntu/actions-runner/_work/NewsClassifier-BERT/NewsClassifier-BERT/app  # Override working directory
        run: |
          docker build -t model-app-2 .
          docker run -d -m 15g -v mlruns_vol:/src/app/volume_mlruns model-app-2 python3 server.py
          docker exec $(docker ps -alq) cp -r volume_mlruns /src/app/mlruns
          docker commit $(docker ps -alq) model-app-2
          docker tag model-app-2:latest ${{ secrets.DOCKER_USERNAME }}/model-app-2:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/model-app-2:latest


